# Generated by Django 4.0.4 on 2022-04-19 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='task')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
